README.md

[doc] moving readme code to be plush

---

form/bootstrap/common.go
form/bootstrap/form_for.go
form/bootstrap/form_for_test.go
form/form_for.go

@markbates this one adds validate support to tags as we discussed on #4, looking forward for your feedback.

[feature] adds validation supports

---

form/form_for.go
form/form_for_test.go

[feature] Allowing users to set custom values on inputs

---

form/bootstrap/form_for_test.go
form/form_for.go

This covers what we discussed on #1 
cc @markbates

[feature] Adding basic support for schema tag

---

form/bootstrap/common.go
form/bootstrap/form_for_test.go

Adds default labels in title case as discussed in #13

[feature] Default labels should be Titleized

---

form/select_tag.go
form/select_tag_test.go
form/selectable.go

Selectable interface implementation

---

README.md

Documents Select Options

---

form/form_for.go
form/form_for_test.go
tag.go
tag_test.go

This PR Adds #24 as well as allowing users to specify a time-format for the value.

[feature] allowing to specify the time format to be set in the value

---

form/bootstrap/form_for_test.go
form/form_for.go

Feature form over schema

---

README.md

Hello!
Thank you so much for this awesome package! 💙 I was recently using it and I couldn't find any documentation for check boxes, so I added a couple of examples about how to use them. 
I hope somebody else finds them useful 😬

Add basic documentation for checkbox usage

---

form/bootstrap/form_for_test.go
form/radio_button.go
form/radio_button_test.go

Allow to auto set the for attribute on radio button's label, using a provided ID.
```erb
<%= f.RadioButton({label: " Water", value: "water", id: "radio-drink-water"}) %>
```
gives:
```html
<label for="radio-drink-water">
<input id="radio-drink-water" type="radio" value="water" /> Water
</label>
```

Auto set the for attribute on label when the ID is provided

---

form/form_for_test.go
form/text_area_test.go
pagination_test.go

@markbates this PR eliminates tags dependency in `github.com/markbates/pop`, will need your blessing before merging it :)

Eliminates Pop dependency

---

form/bootstrap/form.go
form/bootstrap/form_for.go
form/bootstrap/form_for_test.go

Changes the way we render input[type=hidden]

---

misc.go
misc_test.go

adding stylesheet and javascript tags

---

form/bootstrap/common.go
form/bootstrap/form_for.go
form/bootstrap/form_for_test.go
form/checkbox_tag.go
form/form_for.go
form/input_tag.go
form/radio_button.go
form/text_area.go

`tag_only` option can be used for that propose.

Allows to tell bootstrap helper to only generate the tag

---

form/select_tag.go
form/select_tag_test.go

There are some cases it still needs to cover.

Reverting last change to support map keys

---

form/form_for.go
form/radio_button_tag.go
form/select_tag.go
form/select_tag_test.go
form/text_area_tag.go

Adding select map slice support

---

form/bootstrap/form.go
form/form_for.go
form/radio_button_tag.go
form/text_area_tag.go

Removes deprecation warnings and solves an issue @markbates pointed out where the FormFor radio button function could be calling himself infinitely.

Infinite Loop Fix and Cleanup

---

pagination.go
pagination_test.go

Moves our generated pagination to be compatible with Bootstrap 4.

Pagination bootstrap 4

---

.travis.yml
go.mod

@markbates I think this could be helpful, LMK if this doesn't make much sense. I know you should be waay more familiarized with vgo ;).

Adds a go.mod file

---

options.go
options_test.go

```
{data: {remote: true, method: "PUT"}} 
<data-remote="true" data-method="PUT">
```

adds support for nested map options

---

form/select_tag.go
form/select_tag_test.go
form/selectable_multiple.go

Resolved #117
Implement a new interface SelectableMultiple to handle IsSelected to any selectable struc.

Add IsSelected to Selectable with new interface and update Tests

---

form/bootstrap/form_for_test.go
form/checkbox_tag.go
form/checkbox_tag_test.go
form/form_for.go
form/form_for_test.go

Fix Checkbox tag to work in form_for

WIP: Fix checkboxTag for Form_for
